# Generated by Django 2.2.3 on 2019-07-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='created_date',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='revision_date',
            field=models.DateField(null=True, verbose_name='Revision date'),
        ),
    ]
