# Generated by Django 2.2.4 on 2019-10-12 20:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0003_auto_20190727_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='created_date',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='revision_date',
            field=models.DateField(null=True, verbose_name='Revision date'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='PostPage',
        ),
    ]
