# Generated by Django 2.2.4 on 2019-10-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191012_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('plural_title', models.CharField(max_length=125150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('plural_title', models.CharField(max_length=125150)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
