# Generated by Django 2.2.4 on 2019-10-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpagesubtype_blogpagetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagesubtype',
            options={'ordering': ['title']},
        ),
    ]
