# Generated by Django 2.2.4 on 2019-10-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191013_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagesubtype',
            name='sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogPageSubType'),
        ),
        migrations.AddField(
            model_name='blogpagetype',
            name='blog_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogPageType'),
        ),
    ]
