# Generated by Django 2.2.4 on 2019-10-13 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191013_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagetype',
            name='blog_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogPageSubType'),
        ),
        migrations.AlterField(
            model_name='blogpagetype',
            name='filter_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogPageType'),
        ),
    ]
