# Generated by Django 2.2.4 on 2019-10-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191013_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagesubtype',
            name='sub_type',
        ),
        migrations.AlterField(
            model_name='blogpagetype',
            name='plural_title',
            field=models.CharField(max_length=125),
        ),
    ]
