# Generated by Django 2.2.4 on 2019-10-13 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191013_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='page_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogPageType'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='page_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogPageSubType'),
        ),
        migrations.AlterField(
            model_name='blogpagesubtype',
            name='filter_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogPageSubType'),
        ),
    ]
