# Generated by Django 2.2.3 on 2019-07-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
    ]
